### ISSUE TITLE
This vs. iso-8601-date-formatter

### ISSUE THREAD

**Issue by weibel** [soffes/ISO8601#17]
Let me start out with thanking you for working on the ISO parsing for iOS. It's has been a much neglected field, especially when it comes to handling time zones.  

My problem is this: So far we have been using https://github.com/boredzo/iso-8601-date-formatter which has served us relatively well. Now comes along this library, which has started being included some of the other libraries we use. Now we have two ISO parsing libraries in our codebase :-( I want to get rid of one of them.

My request is this: Do you have time to include a short side by side comparison of the pros of using this library vs. iso-8601-date-formatter in the notes? There must have been a reason for doing all this work.

**Comment by soffes** [comment]
I haven't used his in years. It was super slow and way more code compared to what I was doing then.
