### ISSUE TITLE
ISO8601.h missing when using Cocoapods

### ISSUE THREAD

**Issue by sidhantgoyal** [soffes/ISO8601#26]
The latest release `0.5.1` doesn't expose `ISO8601.h` in `.podspec` under sources. 
The recent reorganization of code has moved `ISO8601.h` to `Support` rather than `Sources`.

**Comment by bogosmer** [comment]
+1 - I'm force using 0.5.0 for now

**Comment by mbrooks** [comment]
I'm having to use 0.5.0 as well.

**Comment by soffes** [comment]
Can you try using the pod spec in master? Does that work for you?

**Comment by mbrooks** [comment]
It seems to be working for me now.

**Comment by soffes** [comment]
Thanks! Will release an update now.

**Comment by soffes** [comment]
I can't push 0.5.2 because lint fails due to some error about Watch. Ugh. Maybe @neonichu can help: https://gist.github.com/soffes/3fa2f8fa7ee3bb14225d738aaa42918b

**Comment by neonichu** [comment]
strange, seems like the wrong simulator ID is picked for doing the watchOS build. Could you paste the output of `xcrun simctl list`?

**Comment by soffes** [comment]
Seems to be working on my work iMac. New version is released so closing this issue.

I can check my sim list and open an issue on CocoaPods if you'd like @neonichu.

**Comment by neonichu** [comment]
Yeah, definitely do open an issue — the code dealing with `simctl` parsing lives in https://github.com/neonichu/fourflusher though :+1:
