### ISSUE TITLE
ISO8601String should use GMT timezone

### ISSUE THREAD

**Issue by msanders** [soffes/ISO8601#31]
Currently it uses the [local time zone](https://github.com/soffes/ISO8601/blob/a5e3042604fc6e7cdf6e6ace136fdedf4ff24b70/Sources/NSDate%2BISO8601.m#L47), which is misleading. GMT is used as the default parameter if you pass `nil` to verbose variant, [`ISO8601StringWithTimeZone:usingCalendar:`](https://github.com/soffes/ISO8601/blob/a5e3042604fc6e7cdf6e6ace136fdedf4ff24b70/Sources/NSDate%2BISO8601.m#L56) as well as the inverse method, [`dateWithISO8601String:`](https://github.com/soffes/ISO8601/blob/a5e3042604fc6e7cdf6e6ace136fdedf4ff24b70/Sources/NSDate%2BISO8601.m#L16).

**Comment by soffes** [comment]
Ya :(

Hesitant to make any changes to it now since it's stable for people using in production now and for new apps Apple's ISO8601DateFormatter is preferred.

**Comment by msanders** [comment]
Could increment the [major version](http://semver.org/#spec-item-8) and make note of the incompatible change. Will be a while before everyone can drop iOS 9 support for `ISO8601DateFormatter`.

**Comment by soffes** [comment]
I think it's best until then to use the full version of that method instead of the shorthand version. Sorry.
