### ISSUE TITLE
Improper treatment of Zulu time zone

### ISSUE THREAD

**Issue by calebd** [soffes/ISO8601#5]
Times designated in the `Z` timezone should be returned in `UTC`.

**Comment by soffes** [comment]
Do you have an example?

**Comment by calebd** [comment]
From the readme:

> It's worth noting that a value in the NSDateComponents will be nil if it is not in the input string. For example, 1999-05-19T23:55:21Z will have a nil time zone, but 1999-05-19T23:55:21+00:00 will have a UTC time zone.

Zulu time is synonymous with UTC.

**Comment by soffes** [comment]
Okay, how is it treaded improperly?

**Comment by calebd** [comment]
It looks like the behavior has changed since I opened the issue. It's just the readme that is incorrect.

> 1999-05-19T23:55:21Z will have a nil time zone

**Comment by soffes** [comment]
So that actually has the UTC timezone? I'll have to investigate tonight.
